### ISSUE TITLE
Unicode of  Python2.7 is ucs2, and how to change it?

### ISSUE THREAD

**Issue by lihuimail** [mbachry/exxo#4]
Hello guys!

This project is cool!

The unicode of  python2.7 is ucs2, and how to change it to ucs4?

I change  PYTHON_VERSION_MAP in bootstrap.py, and has error:

make: **\* No rule to make target '/tmp/exxo-master/build/egenix-pyrun-2.1.1/PyRun/Python-2.7.11-ucs4'.  Stop.
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/exxo-master/exxo/bootstrap.py", line 227, in <module>
    main()
  File "/tmp/exxo-master/exxo/bootstrap.py", line 223, in main
    b.bootstrap()
  File "/tmp/exxo-master/exxo/bootstrap.py", line 204, in bootstrap
    self.install_pyrun()
  File "/tmp/exxo-master/exxo/bootstrap.py", line 170, in install_pyrun
    self.pyrun_make(str(python_dir))
  File "/tmp/exxo-master/exxo/bootstrap.py", line 115, in pyrun_make
    cwd=str(self.pyrun_dir))
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j1', '/tmp/exxo-master/build/egenix-pyrun-2.1.1/PyRun/Python-2.7.11-ucs4', 'PYTHONFULLVERSION=2.7.11']' returned non-zero exit status 2
root@IBM:/tmp/exxo-master#

**Comment by mbachry** [comment]
Picking up uc2 as default was a bad choice. I changed it to ucs4 and released a new build (https://bintray.com/artifact/download/mbachry/exxo/exxo-0.0.3.tar.xz). Please carry on and report back any further issues. Any feedback is much appreciated.
