### ISSUE TITLE
building exxo and has error

### ISSUE THREAD

**Issue by lihuimail** [mbachry/exxo#7]
when I build exxo and has error:
config.status: executing buildir commands
config.status: skipping top_srcdir/Makefile - not created
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing include commands
config.status: executing src commands
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/exxo_build/exxo-master-0125/exxo/bootstrap.py", line 229, in <module>
    main()
  File "/home/exxo_build/exxo-master-0125/exxo/bootstrap.py", line 225, in main
    b.bootstrap()
  File "/home/exxo_build/exxo-master-0125/exxo/bootstrap.py", line 206, in bootstrap
    self.install_pyrun()
  File "/home/exxo_build/exxo-master-0125/exxo/bootstrap.py", line 184, in install_pyrun
    self.render_setup_file()
  File "/home/exxo_build/exxo-master-0125/exxo/bootstrap.py", line 153, in render_setup_file
    with tmpl.open() as fp:
  File "/usr/local/lib/python3.4/pathlib.py", line 1073, in open
    opener=self._opener)
  File "/usr/local/lib/python3.4/pathlib.py", line 947, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/local/lib/python3.4/pathlib.py", line 326, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/exxo_build/exxo-master-0125/build/egenix-pyrun-2.1.1/PyRun/Runtime/Setup.PyRun-2.7.tmpl'

and i change bootstrap.py
    def render_setup_file(self):
        fn = 'Setup.PyRun-{}'.format(self.python_major_version)
        - tmpl = self.pyrun_dir / 'Runtime' / (fn + '.tmpl')
        + tmpl = self.pyrun_dir / 'Runtime' / (fn)

is this bug?

**Comment by mbachry** [comment]
It looks like your patch tool version doesn't support git format. Can you paste `patch --version`?

**Comment by lihuimail** [comment]
Think you for reply!

My host is debian lenny. version of patch  is  2.5.9.
I updated  the "patch" from 2.5.9 to 2.7.5, and all is ok :)

ps:
 Lastest version of pip is 8.0.2
